# coding: utf-8

"""
    RIBBIT API v4

    ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from validi_fi_bank_login_python_sdk import ValidiFiBankLogin

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        validifibanklogin = ValidiFiBankLogin(
        )
        self.assertIsNotNone(validifibanklogin)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
