# coding: utf-8

"""
    RIBBIT API v4

    ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import validi_fi_bank_login_python_sdk
from validi_fi_bank_login_python_sdk.model.token_create_request import TokenCreateRequest
from validi_fi_bank_login_python_sdk import configuration


class TestTokenCreateRequest(unittest.TestCase):
    """TokenCreateRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
