# coding: utf-8
"""
    RIBBIT API v4

    ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from validi_fi_bank_login_python_sdk.client_custom import ClientCustom
from validi_fi_bank_login_python_sdk.configuration import Configuration
from validi_fi_bank_login_python_sdk.api_client import ApiClient
from validi_fi_bank_login_python_sdk.type_util import copy_signature
from validi_fi_bank_login_python_sdk.apis.tags.connect_api import CONNECTApi
from validi_fi_bank_login_python_sdk.apis.tags.insights_api import InsightsApi
from validi_fi_bank_login_python_sdk.apis.tags.reports_api import ReportsApi
from validi_fi_bank_login_python_sdk.apis.tags.token_api import TokenApi



class ValidiFiBankLogin(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.connect: CONNECTApi = CONNECTApi(api_client)
        self.insights: InsightsApi = InsightsApi(api_client)
        self.reports: ReportsApi = ReportsApi(api_client)
        self.token: TokenApi = TokenApi(api_client)
