# coding: utf-8

"""
    RIBBIT API v4

    ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from validi_fi_bank_login_python_sdk.paths.v4_connect_banks.get import BankLookup
from validi_fi_bank_login_python_sdk.paths.v4_connect_session.post import CreateSession
from validi_fi_bank_login_python_sdk.paths.v4_accounts_account_token_export.get import GetFullAccountInfo
from validi_fi_bank_login_python_sdk.apis.tags.connect_api_raw import CONNECTApiRaw


class CONNECTApi(
    BankLookup,
    CreateSession,
    GetFullAccountInfo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CONNECTApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CONNECTApiRaw(api_client)
