# coding: utf-8

"""
    RIBBIT API v4

    ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from validi_fi_bank_login_python_sdk.paths.v4_insights_2_inquiry_id.get import GetInsightByIdRaw
from validi_fi_bank_login_python_sdk.paths.v4_insights.post import SubmitLoanApplicationRaw


class InsightsApiRaw(
    GetInsightByIdRaw,
    SubmitLoanApplicationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
