# coding: utf-8

"""
    RIBBIT API v4

    ValidiFI, an analytics and technology company, connects bank account and payment insights to help companies in a variety of industries provide more confident, trustworthy and transparent transactions. Our differentiated data, sourced directly from banks, payment processors, and financial platforms helps companies to ensure compliance, mitigate risk, combat fraud, and confidently validate bank account and ownership. For more information, visit ValidiFI.com.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import validi_fi_bank_login_python_sdk
from validi_fi_bank_login_python_sdk.paths.v4_insights_2_inquiry_id import get
from validi_fi_bank_login_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV4Insights2InquiryId(ApiTestMixin, unittest.TestCase):
    """
    V4Insights2InquiryId unit test stubs
        Get Insights
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
